### ISSUE TITLE
Installation with openhab 2.1 on pi

### ISSUE THREAD

**Issue by asgmxnet** [dfrommi/openhab-tado#6]
just copied all the files from lib to addon. After restart of openhab i get the following exception:
Guess i have to install some libs. For beginners a short "Installation" chapter in the Dokumentation would be nice

2017-12-17 18:56:26.867 [INFO ] [ternal.communicator.client.RpcClient] - Interface 'WIRED' on gateway 'ccu2' not available, disabling support
2017-12-17 18:56:27.994 [ERROR] [slf4j.api                           ] - FrameworkEvent ERROR - slf4j.api
org.osgi.framework.BundleException: Could not resolve module: slf4j.api [189]
  Unresolved requirement: Import-Package: org.slf4j.impl; version="1.6.0"
        at org.eclipse.osgi.container.Module.start(Module.java:434)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1562)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
2017-12-17 18:56:28.071 [ERROR] [org.apache.oltu.oauth2.common       ] - FrameworkEvent ERROR - org.apache.oltu.oauth2.common
org.osgi.framework.BundleException: Could not resolve module: org.apache.oltu.oauth2.common [193]
  Unresolved requirement: Import-Package: org.json
        at org.eclipse.osgi.container.Module.start(Module.java:434)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1562)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
2017-12-17 18:56:28.085 [ERROR] [org.apache.oltu.oauth2.client       ] - FrameworkEvent ERROR - org.apache.oltu.oauth2.client
org.osgi.framework.BundleException: Could not resolve module: org.apache.oltu.oauth2.client [194]
  Unresolved requirement: Import-Package: org.json
        at org.eclipse.osgi.container.Module.start(Module.java:434)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1562)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)[org.eclipse.osgi-3.10.101.v20150820-1432.jar:]
2017-12-17 18:56:41.887 [INFO ] [ternal.communicator.client.RpcClient] - Interface 'HMIP' on gateway 'ccu2' not available, disabling support
2017-12-17 18:56:41.897 [INFO ] [ternal.communicator.client.RpcClient] - Interface 'CUXD' on gateway 'ccu2' not available, disabling support
2017-12-17 18:56:56.919 [INFO

**Comment by Scoobler** [comment]
If you have openHab up to date (if it’s not up to date the first add-on won’t appear), go to paperui, ad-ons, click on the Misc. tab and search for and instal “Eclipse IoT Market”. Once installed click on the Bindings tab you can search for the Tado binding and install it from there.
That is the easiest way I have seen to install the add-on, hope it helps!

**Comment by dfrommi** [comment]
@Scoobler Thanks for the summary. I've added a short section to the README.
